name: Build All

on: [push]

jobs:
  build:
 
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Setup dotnet 6.0.x
      uses: actions/setup-dotnet@v1
      with:
          dotnet-version: '6.0.x'
          include-prerelease: true

    - name: Restore Win64
      run: dotnet restore Facepunch.Steamworks\Facepunch.Steamworks.Win64.csproj
      
    - name: Build Win64
      run: dotnet build Facepunch.Steamworks\Facepunch.Steamworks.Win64.csproj
      
    - name: Build Win64 Release
      run: dotnet build Facepunch.Steamworks\Facepunch.Steamworks.Win64.csproj --configuration Release

    - uses: actions/upload-artifact@v1
      with:
        name: Compiled Files
        path: Facepunch.Steamworks/bin
